# Site settings
name: 张磊涛
location: 沈阳
company: 东北大学
position: 机器人工程师
github: https://github.com/ltiselite
facebook: https://www.facebook.com/
phone: 15524182129
email: 2557186035@qq.com

baseurl: "/zltpage"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

